<?php
//
//
//namespace Drupal\rocket_chat_group\Entity;
//
////* @ConfigEntityType(
//// *   id = "group_type",
//// *   label = @Translation("Group type"),
//// *   label_singular = @Translation("group type"),
//// *   label_plural = @Translation("group types"),
//// *   label_count = @PluralTranslation(
//// *     singular = "@count group type",
//// *     plural = "@count group types"
////  *   ),
//// *   handlers = {
////  *     "access" = "Drupal\group\Entity\Access\GroupTypeAccessControlHandler",
//// *     "form" = {
////    *       "add" = "Drupal\group\Entity\Form\GroupTypeForm",
//// *       "edit" = "Drupal\group\Entity\Form\GroupTypeForm",
//// *       "delete" = "Drupal\group\Entity\Form\GroupTypeDeleteForm"
////      *     },
//// *     "route_provider" = {
////    *       "html" = "Drupal\group\Entity\Routing\GroupTypeRouteProvider",
//// *     },
//// *     "list_builder" = "Drupal\group\Entity\Controller\GroupTypeListBuilder",
//// *   },
//// *   admin_permission = "administer group",
//// *   config_prefix = "type",
//// *   bundle_of = "group",
//// *   static_cache = TRUE,
//// *   entity_keys = {
////  *     "id" = "id",
//// *     "label" = "label"
////    *   },
//// *   links = {
////  *     "add-form" = "/admin/group/types/add",
//// *     "collection" = "/admin/group/types",
//// *     "content-plugins" = "/admin/group/types/manage/{group_type}/content",
//// *     "delete-form" = "/admin/group/types/manage/{group_type}/delete",
//// *     "edit-form" = "/admin/group/types/manage/{group_type}",
//// *     "permissions-form" = "/admin/group/types/manage/{group_type}/permissions"
////    *   },
//// *   config_export = {
////  *     "id",
//// *     "label",
//// *     "description",
//// *     "creator_membership",
//// *     "creator_wizard",
//// *     "creator_roles",
//// *     "ChannelType",
//// *   }
//// * )
//
///**
// * Class GroupType
// *
// * @package Drupal\rocket_chat\group
// *
// */
//class GroupType extends \Drupal\group\Entity\GroupType{
//
//
//  const PRIVATE_CHANNEL = 0b0000;
//  const PUBLIC_CHANNEL  = 0b0001;
//  const BROADCAST       = 0b1000;
//  const WRITE           = 0b0100;
//  const READ            = 0b0010;
//
//
//  /**
//   * @var int Masked value indicateing what type of Channel this uses;
//   */
//  protected $ChannelType = 0b0110;//self::READ & self::WRITE & self::PRIVATE_CHANNEL;
//
//  function get($property_name) {
//    $parent = parent::get($property_name); // TODO: Change the autogenerated stub
//    return  $parent;
//  }
//
//}
